# Make sure to check the documentation at https://goreleaser.com
builds:
  - id: portal
    env:
      # We need to set this to get a statically-linked binary, else we'll get a dynamically-linked binary that won't be able to be run anywhere
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

# In order for releasing-to-Github to work, we have to create these archives
archives:
  - id: portal
    builds:
      - portal
    # Kurtosis is a private repo so we don't want to package any files except the binaries, but GoReleaser by default packages the README, LICENSE, and changelog
    # Worse, setting this to be emptylist won't work because GoReleaser takes emptylist to mean "package the defaults" per:
    #  https://github.com/goreleaser/goreleaser/blob/73641c71ac0d9f78e2409b0cea1bf5b42111b933/internal/pipe/archive/archive.go#L61
    # Therefore, we set this to a glob of files that definitely don't exist
    files:
      - "*THIS_FILE_DOES_NOT_EXIST*"
    name_template: kurtosis-portal_{{ .Version }}_{{ .Os }}_{{ .Arch }}

source:
  enabled: false

checksum:
  name_template: 'checksums.txt'
#snapshot:
#  name_template: "{{ .Env.VERSION }}"
changelog:
  # We manage our own changelog
  skip: true
