# This document explains why this runs on GitHub over Circle
# https://www.notion.so/kurtosistech/Why-we-have-our-Linter-as-a-Github-Action-572b44c4a9b445009515b7b41d5f74ff
# we use `skip-pkg-cache:true` as we run into https://github.com/golangci/golangci-lint-action/issues/244 if we don't

name: Golang Lint

# We only want one run of this on a branch
# if you push another commit the previous run should cancel
concurrency:
  group: "go-linter-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

on:
  push:
    branches:
      - gh-readonly-queue/main/**
  pull_request:

jobs:
  golangci:
    name: golang-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: lint-golang-api
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49.0
          working-directory: api/golang
          args: --timeout=3m
          skip-pkg-cache: true
      - name: lint-daemon
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49.0
          working-directory: daemon
          args: --timeout=3m
          skip-pkg-cache: true
